version: '3.8'

services:
  mongodb:
    image: mongo:4.4.26
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: admin
    command: 
      - "--replSet"
      - "rs0"
      - "--auth"
      - "--keyFile"
      - "/data/keyfile/mongodb-keyfile"
      - "--setParameter"
      - "localLogicalSessionTimeoutMinutes=1"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-keyfile:/data/keyfile/mongodb-keyfile

volumes:
  mongodb_data:
