#!/bin/bash

dir=`date "+%Y-%m-%d"`-$1
mkdir $dir
cd $dir
yarn init -y -2

if [[ "$2" == "ts" ]]; then
  yarn add -D typescript ts-mocha chai mocha @types/mocha @types/chai @types/node
  yarn dlx @yarnpkg/sdks vscode
  node -e "
    const p = require('./package.json')
    p.scripts = {
      test: 'ts-mocha \"src/**/*.test.ts\"',
      'test:watch': 'yarn test -w --watch-files src --reporter min'
    }
    require('fs').writeFileSync('package.json', JSON.stringify(p, null, 2))
  "

  echo '{
  "compilerOptions": {
    "module": "CommonJS",
    "target": "ES2021",
    "strict": true
  }
}' > tsconfig.json

  mkdir src

  echo "import {expect} from 'chai'

it('works', () => {
  expect(true).to.be.true
})" > src/example.test.ts

  echo 'For safety reason VSCode requires you to explicitly activate the custom TS settings:'
  echo ' - Press ctrl+shift+p in a TypeScript file'
  echo ' - Choose "Select TypeScript Version'
  echo ' - Pick "Use Workspace Version"'
  echo 'See also: https://yarnpkg.com/getting-started/editor-sdks#vscode'

fi

cd ..
code $dir
