kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-world
  labels:
    k8s-app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: hello-world
  template:
    metadata:
      labels:
        k8s-app: hello-world
    spec:
      containers:
        - name: hello-world
          image: hello-world:04-29-20-16-04-00
          imagePullPolicy: Never
          ports:
          - containerPort: 3000