#!/bin/bash

# Function to handle the termination of both scripts
cleanup() {
  pkill -P $pid1
  pkill -P $pid2
  exit 1
}

# Trap SIGINT (Ctrl-C) and call cleanup function
trap cleanup SIGINT

# Run script1.sh and script2.sh in the background
./simulate $1 &
pid1=$!

sleep 3

./render $1 &
pid2=$!

# Wait for both scripts to finish
wait $pid1
wait $pid2
