version: '3.1'

services:
  db:
    image: postgres:10-alpine
    volumes:
      - /var/lib/postgresql/data
      - ./src/init-db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'