[package]
name = "simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
rmp = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
rmp-serde = "1.3.0"