[package]
name = "rust-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"  # or the latest version
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
rmp = "0.8"  # or the latest version for msgpack