version: '3'

services:
  db:
    image: postgres:10-alpine
    expose:
      - '5432'
    ports:
      - '4237:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: guides